global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mylittleprice'

scrape_configs:
  - job_name: 'mylittleprice_backend'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
